### PR TITLE
Update module for FVTT10

### PR DESCRIPTION
**Pull request by p4535992**
I update the project for fvtt10 and add some features i founded useful with this module (if you don't like i can just remove these)

### CODE REVIEW

**Comment by manuelVo** [comment]
Hi. Thanks for the PR. Are you able to condense the PR down to only the changes that are necessary for v10 compatibility?

**Comment by p4535992** [comment]
- I removed all the non-essential configuration files.
- I removed the github workflows
- I moved all the code under the "src" folder because I think it is more "correct" to separate the real code from the configuration files and simplifies the creation of the "module.zip" (I basically zip the src folder directly when i need to do a release).
- The feature to disable the viewing and animation of tokens during drag and drop for GMs was requested by a third party and I think it is in line with the use of the module is however configurable from a module setting .
- put everything on the single main.js file (removed setting.js and constants,js ).

The even more condensed solution is to replace only the text 'SightLayer.prototype.tokenVision' with 'CanvasVisibility.prototype.tokenVision', but I would like to insist on the integration of the additional features

**Comment by p4535992** [comment]
@manuelVo just a reminder for this

**Comment by manuelVo** [comment]
Thanks for your pointers on what to do. I've just pushed a v10 compatible version based on your input. Regarding the feature to disable token animations, I feel like that would be a better fit for a separate module. It's certainly a useful feature for GMs. However, apart from the shared target audience, I don't see any commonalities between that feature and this module. Feel free to correct me on this if I'm wrong.

**Comment by p4535992** [comment]
no problem at all i will open a pr just for the readme file

**Pull request closed without merging**
